### ISSUE TITLE
Add users feature

### ISSUE THREAD

**Issue by jessicapatwa** [ctedtsen/Rescue-Dog-Discovery-Tool#23]

**Comment by jessicapatwa** [comment]
Updated users.js

Output Screenshots

http://localhost:3000/
<img width="625" alt="Screenshot " src="https://user-images.githubusercontent.com/52906778/208041192-1c0b3a02-7e81-481d-9cb7-f7c932227c29.png">

http://localhost:3000/register
<img width="337" alt="Screenshot 2" src="https://user-images.githubusercontent.com/52906778/208041428-38c624be-110f-4811-a1ec-5adf52eb8683.png">

**Comment by Jasmine211** [comment]
Hi, thank you for the form demos, but this feature is already implemented and pushed to the main branch.
